class Zigporter < Formula
  include Language::Python::Virtualenv

  desc "CLI toolkit for Zigbee device management in Home Assistant"
  homepage "https://github.com/nordstad/zigporter"
  url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
  sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  license "MIT"

  depends_on "rust" => :build # required for pydantic-core
  depends_on "python@3.13"

  # --- resource stanzas (generated by: brew update-python-resources Formula/zigporter.rb) ---

  resource "annotated-doc" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "annotated-types" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "anyio" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "certifi" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "h11" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "httpcore" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "httpx" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "idna" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "markdown-it-py" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "mdurl" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "prompt-toolkit" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "pydantic" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "pydantic-core" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "pygments" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "python-dotenv" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "questionary" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "rich" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "shellingham" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "svgwrite" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "typer" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "typing-extensions" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "typing-inspection" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "wcwidth" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  resource "websockets" do
    url "https://files.pythonhosted.org/packages/c3/97/a37110a80254c74d7e9f95d2a097123bab6c0b00636e60a0fb3c98bd41a6/zigporter-1.4.0.tar.gz"
    sha256 "0568997acaa99617862c97cb39fcf115d738fc1720ffb5db69a03ee10c003fef"
  end

  def install
    virtualenv_install_with_resources

    # Typer's --show-completion relies on shellingham to detect the parent shell,
    # which fails in a build sandbox. Generate completion scripts via Typer's
    # Python API directly to avoid that dependency on process introspection.
    py = libexec/"bin/python"
    {
      bash_completion/"zigporter"      => "bash",
      zsh_completion/"_zigporter"      => "zsh",
      fish_completion/"zigporter.fish" => "fish",
    }.each do |path, shell|
      path.write Utils.safe_popen_read(
        py, "-c",
        "from typer.completion import get_completion_script; " \
        "print(get_completion_script(" \
        "prog_name='zigporter', complete_var='_ZIGPORTER_COMPLETE', shell='#{shell}'))"
      )
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zigporter --version")
  end
end
